class TestMicrosoft:
    def test_translate_word():
        ...

    def test_translate_sentence():
        ...

    def test_format_word_response():
        ...

    def test_format_sentence_response():
        ...

    def test_download_audio_file():
        ...
