name: check pwd
on:
  pull_request:
  push:
  workflow_dispatch:
#   schedule:
#     - cron: "0 4 * * *" # run once a day at 4 AM
jobs:
  scan:
    name: check pwd
    runs-on: ubuntu-latest
    steps:
       # 1. 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # truffleHog 检查密码
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.88.0

      # gitleaks 检查密码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}} # Only required for Organizations, not personal accounts.